# Generated by Django 2.0 on 2020-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='yunicon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='icon',
            field=models.ImageField(default='uploads/minel.png', upload_to='uploads/%Y/%m/%d'),
        ),
    ]
