# Generated by Django 2.0 on 2020-03-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200326_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='icon',
        ),
    ]
